name: Build App, package and export to artifacts

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
    
permissions:
  contents: read
  pages: write
  id-token: write

concurrency:
  group: "pages"
  cancel-in-progress: false

jobs:
  # build job
  build_app:
    runs-on: ubuntu-latest
    
    defaults:
      run:
        working-directory: ./cofmupy-gui-app

    strategy:
      matrix:
        node-version: [20, 22]
    
    steps:
    - uses: actions/checkout@v4

    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v4
      with:
        node-version: ${{ matrix.node-version }}
        cache: 'npm'
        cache-dependency-path: '**/package-lock.json'
        
    - name: Install Dependencies
      run: npm ci
        
    - name: Build
      run: |
        ./node_modules/.bin/ng build
        ls ./dist/cofmupy-gui

    - name: Upload build as artifact
      uses: actions/upload-artifact@v4
      with:
        name: cofmupy-gui_V${{ matrix.node-version }}
        path: './cofmupy-gui-app/dist/cofmupy-gui/browser'
  
  # Deploy app
  deploy_app:
    needs: [build_app]
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/download-artifact@v4
        with:
          name: cofmupy-gui_V20
          path: './deployed_app'
      - name: Move files
        working-directory: ./deployed_app
        run: |
          mv ./assets/*.bat .
          mv ./assets/*.sh .

      - name: Upload build as final artifact
        uses: actions/upload-artifact@v4
        with:
          name: cofmupy-gui_final
          path: './deployed_app'
      - name: Clean artifacts
        uses: actions/delete_artifact@v4
        with:
          name: |
            cofmupy-gui_V20
            cofmupy-gui_V22


      

